services:
  db:
    container_name: versus_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: versus
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    container_name: versus_api
    build:
      context: .
      dockerfile: src/Versus.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
        - db

volumes:
  postgres-data:
