services:
  versus.db:
    container_name: versus_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: versus
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  versus.host:
    container_name: versus_host
    build:
      context: .
      dockerfile: src/Versus.Host/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
        - versus.db

volumes:
  postgres_data: