# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: versus_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Checkout Versus.api
      uses: actions/checkout@v4
      with:
        path: Versus.api

    - name: Checkout Versus.Shared
      uses: actions/checkout@v4
      with:
        repository: KondzioBondzio/Versus.Shared
        path: Versus.shared

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      working-directory: ./Versus.api
      run: dotnet restore

    - name: Build
      working-directory: ./Versus.api
      run: dotnet build --no-restore

    - name: Test
      working-directory: ./Versus.api
      run: dotnet test --no-build --verbosity normal
